<?php

namespace App\Services;

use App\Models\AmenConversation;
use App\Models\User;
use Illuminate\Support\Facades\Http;
use Illuminate\Support\Facades\Log;
use Illuminate\Support\Str;
use RuntimeException;

/**
 * AmenAIService — The core Amen AI chat engine.
 *
 * Orchestrates the full conversation flow:
 * 1. Query Knowledge Bank for relevant Custodian fragments
 * 2. Build system prompt (v9.0 spec) with optional fragment injection
 * 3. Call AI provider (OpenAI active / Claude ready for future swap)
 * 4. Log citation if Knowledge Bank fragment was used
 * 5. Save conversation history for continuity + future fine-tuning
 *
 * Provider switching is controlled by AMEN_AI_PROVIDER env variable.
 * Set to "openai" (default) or "anthropic" (future).
 */
class AmenAIService
{
    public function __construct(
        private KnowledgeBankService $knowledgeBankService,
    ) {}

    // ──────────────────────────────────────────────────────────────
    // Public API
    // ──────────────────────────────────────────────────────────────

    /**
     * Process a chat message and return Amen's response.
     *
     * @param string $message         The client's message
     * @param string $conversationId  Session UUID (generated by frontend)
     * @param User   $client          The authenticated user
     *
     * @return array{
     *   response: string,
     *   conversation_id: string,
     *   fragment_used: bool,
     *   custodian_name: ?string,
     *   custodian_region: ?string,
     *   model_used: string,
     * }
     */
    public function chat(string $message, string $conversationId, User $client): array
    {
        // Step 1: Save the user's message to conversation history
        $this->saveMessage($client->id, $conversationId, 'user', $message);

        // Step 2: Query Knowledge Bank for relevant fragments
        $fragment = $this->knowledgeBankService->queryKnowledgeBank($message);

        // Step 3: Load conversation history for context
        $history = $this->getConversationHistory($conversationId);

        // Step 4: Build the system prompt with optional fragment injection
        $systemPrompt = $this->buildSystemPrompt($fragment);

        // Step 5: Build messages array for the AI provider
        $messages = $this->buildMessages($history, $message, $systemPrompt);

        // Step 6: Call the AI provider
        $provider = config('ai.provider', 'openai');
        $result = $this->callProvider($provider, $messages, $systemPrompt);

        $responseText = $result['content'];
        $modelUsed = $result['model'];
        $tokensUsed = $result['tokens'] ?? null;

        // Step 7: If a Knowledge Bank fragment was used, log the citation
        $fragmentUsed = $fragment !== null;
        if ($fragmentUsed && isset($fragment['contribution_id'], $fragment['custodian_user_id'])) {
            $this->knowledgeBankService->logCitation(
                contributionId: (int) $fragment['contribution_id'],
                custodianId: (int) $fragment['custodian_user_id'],
                clientId: $client->id,
                conversationId: $conversationId,
                pineconeScore: $fragment['score'] ?? 0.0,
            );
        }

        // Step 8: Save Amen's response to conversation history
        $this->saveMessage(
            userId: $client->id,
            conversationId: $conversationId,
            role: 'assistant',
            content: $responseText,
            fragmentUsed: $fragmentUsed,
            contributionId: $fragment['contribution_id'] ?? null,
            modelUsed: $modelUsed,
            tokensUsed: $tokensUsed,
        );

        return [
            'response'         => $responseText,
            'conversation_id'  => $conversationId,
            'fragment_used'    => $fragmentUsed,
            'custodian_name'   => $fragment['custodian_name'] ?? null,
            'custodian_region' => $fragment['custodian_region'] ?? null,
            'model_used'       => $modelUsed,
        ];
    }

    /**
     * Get the conversation history for a user.
     */
    public function getUserConversations(int $userId): array
    {
        return AmenConversation::where('user_id', $userId)
            ->selectRaw('conversation_id, MIN(created_at) as started_at, MAX(created_at) as last_message_at, COUNT(*) as message_count')
            ->groupBy('conversation_id')
            ->orderByDesc('last_message_at')
            ->limit(20)
            ->get()
            ->toArray();
    }

    /**
     * Get messages for a specific conversation session.
     */
    public function getConversationMessages(string $conversationId, int $userId): array
    {
        return AmenConversation::where('conversation_id', $conversationId)
            ->where('user_id', $userId)
            ->orderBy('created_at', 'asc')
            ->get()
            ->map(fn($msg) => [
                'id'              => $msg->id,
                'role'            => $msg->role,
                'content'         => $msg->content,
                'fragment_used'   => $msg->fragment_used,
                'timestamp'       => $msg->created_at->toISOString(),
            ])
            ->toArray();
    }

    // ──────────────────────────────────────────────────────────────
    // AI Provider Calls
    // ──────────────────────────────────────────────────────────────

    /**
     * Route the request to the configured AI provider.
     */
    private function callProvider(string $provider, array $messages, string $systemPrompt): array
    {
        return match ($provider) {
            'openai'    => $this->callOpenAI($messages),
            'anthropic' => $this->callAnthropic($messages, $systemPrompt),
            default     => throw new RuntimeException("Unknown AI provider: {$provider}"),
        };
    }

    /**
     * Call OpenAI Chat Completions API (GPT-4o).
     *
     * This is the ACTIVE provider for Amen AI.
     */
    private function callOpenAI(array $messages): array
    {
        $apiKey = config('ai.openai.api_key');
        $model = config('ai.openai.model', 'gpt-4o');
        $maxTokens = config('ai.openai.max_tokens', 1024);
        $temperature = config('ai.openai.temperature', 0.7);

        if (empty($apiKey)) {
            throw new RuntimeException('OPENAI_API_KEY is not configured.');
        }

        $response = Http::withHeaders([
            'Authorization' => "Bearer {$apiKey}",
            'Content-Type'  => 'application/json',
        ])
        ->timeout(60)
        ->post('https://api.openai.com/v1/chat/completions', [
            'model'       => $model,
            'messages'    => $messages,
            'max_tokens'  => $maxTokens,
            'temperature' => $temperature,
        ]);

        if (!$response->successful()) {
            Log::error('OpenAI Chat API error', [
                'status' => $response->status(),
                'body'   => $response->body(),
            ]);
            throw new RuntimeException(
                "OpenAI Chat API error ({$response->status()}): {$response->body()}"
            );
        }

        $data = $response->json();

        return [
            'content' => $data['choices'][0]['message']['content'] ?? '',
            'model'   => $model,
            'tokens'  => $data['usage']['total_tokens'] ?? null,
        ];
    }

    /**
     * Call Anthropic Claude API.
     *
     * FUTURE PROVIDER — Ready to activate by setting AMEN_AI_PROVIDER=anthropic.
     * Claude uses a different message format where system prompt is a top-level field.
     */
    private function callAnthropic(array $messages, string $systemPrompt): array
    {
        $apiKey = config('ai.anthropic.api_key');
        $model = config('ai.anthropic.model_heavy', 'claude-sonnet-4-20250514');
        $maxTokens = config('ai.anthropic.max_tokens', 1024);

        if (empty($apiKey)) {
            throw new RuntimeException('ANTHROPIC_API_KEY is not configured.');
        }

        // Claude expects system prompt as a top-level field, not in messages array
        // Filter out the system message from the messages array
        $claudeMessages = array_values(array_filter($messages, fn($m) => $m['role'] !== 'system'));

        $response = Http::withHeaders([
            'x-api-key'         => $apiKey,
            'anthropic-version' => '2023-06-01',
            'Content-Type'      => 'application/json',
        ])
        ->timeout(60)
        ->post('https://api.anthropic.com/v1/messages', [
            'model'      => $model,
            'max_tokens' => $maxTokens,
            'system'     => $systemPrompt,
            'messages'   => $claudeMessages,
        ]);

        if (!$response->successful()) {
            Log::error('Anthropic Claude API error', [
                'status' => $response->status(),
                'body'   => $response->body(),
            ]);
            throw new RuntimeException(
                "Anthropic API error ({$response->status()}): {$response->body()}"
            );
        }

        $data = $response->json();

        return [
            'content' => $data['content'][0]['text'] ?? '',
            'model'   => $model,
            'tokens'  => ($data['usage']['input_tokens'] ?? 0) + ($data['usage']['output_tokens'] ?? 0),
        ];
    }

    // ──────────────────────────────────────────────────────────────
    // System Prompt Construction (v9.0 Spec)
    // ──────────────────────────────────────────────────────────────

    /**
     * Build the complete system prompt, injecting a Knowledge Bank fragment
     * if one was found above the confidence threshold.
     *
     * @see Training Spec v9.0, Part 10
     */
    private function buildSystemPrompt(?array $fragment): string
    {
        $promptPath = storage_path('ai/amen_system_prompt_v9.txt');

        if (file_exists($promptPath)) {
            $basePrompt = file_get_contents($promptPath);
        } else {
            // Fallback: use inline prompt if file doesn't exist yet
            $basePrompt = $this->getDefaultSystemPrompt();
        }

        if ($fragment) {
            $attribution = "{$fragment['custodian_name']} ({$fragment['custodian_region']})";
            $fragmentBlock = "CUSTODIAN: {$attribution}\nKNOWLEDGE: {$fragment['fragment_text']}";

            $basePrompt = str_replace(
                '[KNOWLEDGE_BANK_FRAGMENT_HERE]',
                $fragmentBlock,
                $basePrompt
            );
        } else {
            $basePrompt = str_replace(
                "KNOWLEDGE BANK FRAGMENT (injected by Laravel if Pinecone score ≥ 0.78):\n[KNOWLEDGE_BANK_FRAGMENT_HERE]",
                "[No Knowledge Bank fragment matched this query. Use general cultural knowledge base only. Do not fabricate Custodian content.]",
                $basePrompt
            );
        }

        return $basePrompt;
    }

    /**
     * Build the messages array for the AI provider.
     *
     * Includes system prompt, recent conversation history, and the current message.
     */
    private function buildMessages(array $history, string $currentMessage, string $systemPrompt): array
    {
        $messages = [
            ['role' => 'system', 'content' => $systemPrompt],
        ];

        // Add recent conversation history (last 20 messages for context window)
        $recentHistory = array_slice($history, -20);
        foreach ($recentHistory as $msg) {
            $messages[] = [
                'role'    => $msg['role'],
                'content' => $msg['content'],
            ];
        }

        // Add the current user message
        $messages[] = [
            'role'    => 'user',
            'content' => $currentMessage,
        ];

        return $messages;
    }

    // ──────────────────────────────────────────────────────────────
    // Conversation History
    // ──────────────────────────────────────────────────────────────

    /**
     * Load conversation history from the database.
     */
    private function getConversationHistory(string $conversationId): array
    {
        return AmenConversation::forSession($conversationId)
            ->get()
            ->map(fn($msg) => [
                'role'    => $msg->role,
                'content' => $msg->content,
            ])
            ->toArray();
    }

    /**
     * Save a message to the conversation log.
     */
    private function saveMessage(
        int $userId,
        string $conversationId,
        string $role,
        string $content,
        bool $fragmentUsed = false,
        ?int $contributionId = null,
        ?string $modelUsed = null,
        ?int $tokensUsed = null,
    ): void {
        AmenConversation::create([
            'user_id'         => $userId,
            'conversation_id' => $conversationId,
            'role'            => $role,
            'content'         => $content,
            'fragment_used'   => $fragmentUsed,
            'contribution_id' => $contributionId,
            'model_used'      => $modelUsed,
            'tokens_used'     => $tokensUsed,
        ]);
    }

    // ──────────────────────────────────────────────────────────────
    // Default System Prompt (fallback if file not found)
    // ──────────────────────────────────────────────────────────────

    /**
     * The production system prompt from the v9.0 Training Spec.
     * This is used as a fallback if storage/ai/amen_system_prompt_v9.txt doesn't exist.
     */
    private function getDefaultSystemPrompt(): string
    {
        return <<<'PROMPT'
You are Amen, the digital companion of OurRoots.Africa.

Your name means "the hidden one" in Ancient Egyptian. You walk alongside, unseen but present.

You are a griot — a keeper of stories, a cultural bridge, a gentle witness to homecoming. You are not a therapist, tour guide, or chatbot.

Your client, Amara, is a third-generation African-American returning to Ghana for the first time. She carries ancestral grief, identity anxiety, and profound longing. She is not your customer. She is a relative making her way home.

VOICE: Speak like a wise elder aunt. Simple and specific. Present and direct. Slightly literary. Cultural without performing.

NEVER SAY: "I understand how you feel" / "It's okay" / "Don't worry" / "At least..." / "Tour" / "User" / "Customer" / "As an AI..."

ALWAYS: Hold before fixing. Validate contradiction. Name the collective. One question per message — usually zero.

CRISIS: If client signals crisis, send grounding instructions (5-sense technique), escalate to Custodian, alert platform immediately.

PROVERBS: Use sparingly — one per conversation maximum. Never to perform knowledge.

LANGUAGES: Respond in the language the client writes in. If they write in Twi or another African language, respond in kind.

KNOWLEDGE BANK: When a verified Knowledge Bank fragment is injected below, you MUST:
1. Use the Custodian's knowledge as the primary source for your answer.
2. Always attribute: name the Custodian by their full name and region/ethnic group.
3. Never paraphrase to the point of losing attribution. You may weave their words naturally into your response, but the Custodian's name must appear.
4. Never present Knowledge Bank content as your own knowledge or as general cultural fact without attribution.
5. If the fragment includes a direct quote from the Custodian, preserve it in quotation marks.
6. The citation earns the Custodian $0.35. Treat attribution as an act of economic justice, not just courtesy.

KNOWLEDGE BANK FRAGMENT (injected by Laravel if Pinecone score ≥ 0.78):
[KNOWLEDGE_BANK_FRAGMENT_HERE]

If no fragment is injected, fall back to the general cultural knowledge base in this specification. Do NOT fabricate Custodian names or fragment content.

CULTURAL KNOWLEDGE CONTEXT:

The Core Identity Wound: The diaspora experience carries a specific wound — belonging nowhere completely. Never make her justify her connection. The land does not require a passport. The ancestors do not check credentials.

Ancestral Grief: Many diaspora travellers carry ancestral grief at heritage sites — particularly Cape Coast Castle. This is not fragility. This is depth. Treat it as sacred.

"Am I African Enough?": Never argue against the feeling. Hold it and expand the frame. "The language did not follow you to Atlanta. That was not your fault. But something did follow — something underneath language, underneath custom. That is what brought you back."

The Disappointment Gap: Between imagination and arrival, there is often a gap. Do not fix it. Help her hold both.

Ubuntu: "Umuntu ngumuntu ngabantu" — A person is a person through other people. African identity is relational, not isolated.

Ancestor Reverence: In most West African traditional belief systems, the dead are not fully gone. They are present, watchful, capable of relationship with the living.

PROVERB LIBRARY (use sparingly):
- Akan: "Ɔhɔhoɔ ani akɛseɛ nanso ɔnhunu hwee." — "The stranger has big eyes but sees nothing."
- Akan: "Nyansa nni onipa baako tirim." — "Wisdom is not in the head of one person."
- Fante: "Nusu ne asuo a ɛde wo kɔ fie." — "Tears are the river that takes you home."
- Universal: "The child who is not embraced by the village will burn it down to feel its warmth."
PROMPT;
    }
}
